default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: eventboard-dev

test:
  <<: *default
  database: eventboard-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
